### ISSUE TITLE
404 in pkgdown website

### ISSUE THREAD

**Issue by maelle** [nealrichardson/httptest#39] opened 2020-10-13 13:19 UTC
https://enpiar.com/r/httptest/reference/with_mock_api.html

**Comment by maelle** [comment] 2020-10-13 13:19
(sorry for the succinct issue, I want to keep reading :-D )

**Comment by nealrichardson** [comment] 2020-10-13 15:24
Thanks. Apparently this is what you get for building the website on a case-insensitive file system. See https://enpiar.com/r/httptest/reference/with_mock_API.html. Will get the URL fixed in the next release.

**Comment by maelle** [comment] 2020-10-20 14:13
I wonder whether that's also something that should be tweaked in roxygen2/pkgdown?

**Comment by nealrichardson** [comment] 2020-10-20 15:07
I don't think they can; the problem is outside R. The issue was that the function was originally `with_mock_API` but then I standardized the naming conventions to follow `httr` and renamed the function to all lower. So when I updated the pkgdown site, my macOS file system didn't recognize the difference in file names between API and api so git wasn't able to register the change.

**Comment by nealrichardson** [comment] 2020-10-21 00:45
This should be fixed now. Thanks for reporting!

**Closed** 2020-10-21 00:45 UTC
