### ISSUE TITLE
Package redactors should load when testing interactively with devtools::test()

### ISSUE THREAD

**Issue by MarkEdmondson1234** [nealrichardson/httptest#15] opened 2018-08-18 13:41 UTC
Hello!

I've tried this:
> You can also provide this function in inst/httptest/request.R, and any time your package is loaded (as when you run tests or build vignettes), this function will be called automatically. 

With this code:

```r
set_requester(function (request) {
  gsub_request(request, "https\\://(.+).googleapis.com/", "api/")
})
```

...but the mocks are still written to the long form folders, without substitution.  Am I missing something?

Its for this repo https://github.com/ropensci/googleLanguageR/blob/master/inst/httptest/request.R and the mocks are here https://github.com/ropensci/googleLanguageR/tree/master/tests

**Comment by nealrichardson** [comment] 2018-08-20 03:35
Ok, good to know. I can look into what `devtools::test()` does exactly and see if I can make it work in the interactive case. I'll renaming this issue to focus on that.

As you note, it does work as expected in `R CMD check` (and hence Travis) because the package is "properly" installed--I even have [a test](https://github.com/nealrichardson/httptest/blob/master/tests/testthat/test-find-redactor.R#L40) that it finds the redactor from an installed package.

**Comment by MarkEdmondson1234** [comment] 2018-08-27 20:52
Now for some reason the Travis tests are failing https://travis-ci.org/ropensci/googleLanguageR/builds/417955023

...but the local (via `devtools::check()`) do work.  I'm confused why they should differ since its the same code in both cases. 

```
sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.0     magrittr_1.5       R6_2.2.2           assertthat_0.2.0   parallel_3.5.0    
 [6] tools_3.5.0        yaml_2.1.19        testthat_2.0.0     rlang_0.2.2        stringdist_0.9.5.1
```

**Comment by nealrichardson** [comment] 2018-08-27 21:40
Looks like a github problem to me: `The command "eval git fetch origin +refs/pull/43/merge: " failed 3 times.`

**Comment by MarkEdmondson1234** [comment] 2019-01-26 21:09
Just a note I spent 30mins puzzling why this didn't work again until I read this thread, so may be worth adding a note to the website in the FAQ

**Comment by MarkEdmondson1234** [comment] 2019-01-26 21:40
And still confusingly it still errors on Travis - I can do the steps above to create the mocks, but then they fail.  Any hints appreciated - The [travis build log](https://travis-ci.org/ropensci/googleLanguageR/builds/484856473) and [github commit](https://github.com/ropensci/googleLanguageR/commit/4824eb9c31e7226319e2e26308618da09864353f)

**Comment by nealrichardson** [comment] 2019-01-28 18:01
Thanks for the nudge on this issue, I'll take another look. I'd rather add a solution than a note to the FAQ, which wouldn't prevent you or someone else from losing time on the issue.

Re: the travis build, the test failures all say "Invalid token", not an `httptest` error from not finding a mock. Maybe that is trapped somewhere in your code and returned as `Invalid token`? Or maybe it's something else.

**Comment by nealrichardson** [comment] 2019-01-28 22:43
Alright, give that a try and see if it is resolved. I believe I reproduced the behavior faithfully in the test, but it's possible that there's some other corner I missed.

**Comment by MarkEdmondson1234** [comment] 2019-02-08 20:27
I'm afraid it has not, with this commit I have the redact.R and request.R with this content:

```r
function(response){
  require(magrittr, quietly=TRUE)
  response %>%
    httptest::gsub_response(".googleapis.com", "", fixed=TRUE)
}
```

```r
function(request){
   require(magrittr, quietly=TRUE)
   request %>%
       httptest::gsub_response(".googleapis.com", "", fixed=TRUE)
}
```

I expect these redactions to turn `language.googleapis.com` into `language` etc.


* Set my INTEGRATION_TESTS <- TRUE flag in my ["prep_tests.R" file](https://github.com/ropensci/googleLanguageR/blob/master/tests/testthat/prep_tests.R) that sets this line:
`  with_mock_api <- httptest::capture_requests`
* Make sure my authentication is on via `GL_AUTH` environment file.
* I "Install and Restart" in RStudio
* Click the "more > test package" button in RStudio
* wait for tests to run

The expected folders are not created - they stay the same as before with `language.googleapis.com` etc.

Then I think I have another issue, where the authentication token is not recognised after the first run - will investigate that a bit and open another issue if necessary.

**Comment by nealrichardson** [comment] 2019-02-08 22:40
Ok. I'll have to look into what "Install and Restart" does then. Instead of doing that step, could you try just `pkgload::load_all()`?

**Comment by ramiromagno** [comment] 2019-04-14 00:56
hi @nealrichardson:

I am also having the same trouble. The mocks files are written to the long form folders, without substitution... I might be doing something wrong too as I have just started attempting at shortening those long URLs because of the "non-portable file paths" during `R CMD check`. Still, if you could have a look at my code it would be great!

https://github.com/ramiromagno/gwasrapidd/tree/master/inst/httptest

P.S.: @MarkEdmondson1234 's last post includes the code for both `redact.R` and `request.R` but both use the function `gsub_response`. Should not he be using `gsub_request` in `request.R` instead?

Many thanks!

**Comment by ramiromagno** [comment] 2019-04-14 01:04
Now I am seeing the same pattern as @MarkEdmondson1234. Travis builds fail, `devtools::check()` also fails but running `devtools::test()` works without any fail...

**Comment by ramiromagno** [comment] 2019-04-14 01:07
Well, closing and opening RStudio now made the writing of the mock files work...

```
Using redact.R from “gwasrapidd”

Attaching package: ‘magrittr’

The following objects are masked from ‘package:testthat’:

    equals, is_less_than, not

Writing /home/rmagno/sci/code/R/pkg/gwasrapidd/tests/testthat/gc/metadata.json
```

**Comment by nealrichardson** [comment] 2019-04-15 22:31
Hi @ramiromagno, 
For (1), could you try with the github version of `httptest`? `devtools::test()` ignoring the request preprocessor sounds like it could be the `pkgload::load_all()` issue I fixed most recently. 

For (2), I looked for a failing Travis build of yours and saw https://travis-ci.org/ramiromagno/gwasrapidd/jobs/519796371, and the failure makes sense because as you note, the request preprocessor is running but you don't have the mocks in the new location (according to what I see in the corresponding commit, https://github.com/ramiromagno/gwasrapidd/tree/2f7f79dc314d3a1559d8096792f0a155178af689/tests/testthat).

Interesting observation about Mark's request.R using `gsub_response()` instead of `gsub_request()`. That could affect whether request body and query parameters are properly handled, but both apply to `$url`, which is where the path shortening will happen. (See https://github.com/nealrichardson/httptest/blob/master/R/redact.R#L88-L112) So it could cause problems, but probably not _these_ problems.

**Comment by ramiromagno** [comment] 2019-04-16 00:03
Hi @nealrichardson,

After installing the github version of `httptest` I am getting a very interesting behavior... Depending on where I call `devtools::test()` it uses the request preprocessor or not, and not consistently. Sometimes, hitting Shift+Ctrl+d that runs `devtools::test()` "at the top right" pane I get tests passing, meaning using the shortened mock paths, while running `devtools::test()` directly from the console won't work, i.e. it is still trying to test using the long paths... Some other times is the other way around! From the console it works but runnning `devtools::test()` via the shortcut does not...

Here's a screenshot illustrating the first case: `devtools::test()` ran from the console does not use the shortened paths but seemingly `devtools::test()` ran via the Shift+Ctrl+d does work... I am very confused.

![Screenshot from 2019-04-16 01-00-25](https://user-images.githubusercontent.com/19862384/56172898-57fe2880-5fe3-11e9-8fbf-71924c437920.png)

**Comment by ramiromagno** [comment] 2019-04-16 00:22
BTW: How do I do the substitutions for multiple patterns? I tried this but it's not working:

`inst/httptest/redact.R`:

```R
httptest::set_redactor(
  list(
    function (response) { httptest::gsub_response(response, "https\\://www.ebi.ac.uk/gwas/rest/api/", "gc/") },
    function (response) { httptest::gsub_response(response, "https:\\://www.ebi.ac.uk/efo/", "efo/") },
    function (response) { httptest::gsub_response(response, "https:\\://www.ebi.ac.uk/ols/api/ontologies/efo", "ols/") }
  )
)
```
`inst/httptest/request.R`:
```R
httptest::set_requester(
  list(
    function (request) { httptest::gsub_request(request, "https\\://www.ebi.ac.uk/gwas/rest/api/", "gc/") },
    function (request) { httptest::gsub_request(request, "https:\\://www.ebi.ac.uk/efo/", "efo/") },
    function (request) { httptest::gsub_request(request, "https:\\://www.ebi.ac.uk/ols/api/ontologies/efo", "ols/") }
  )
)
```

**Comment by nealrichardson** [comment] 2019-04-16 20:56
`set_requester`/`set_redactor` take a single function, so more like:

```r
set_redactor(function (response) {
    response %>%
        gsub_response("https\\://www.ebi.ac.uk/gwas/rest/api/", "gc/") %>%
        gsub_response("https:\\://www.ebi.ac.uk/efo/", "efo/") %>%
        gsub_response("https:\\://www.ebi.ac.uk/ols/api/ontologies/efo", "ols/")
})
```

**Comment by ramiromagno** [comment] 2019-04-17 09:10
@nealrichardson: Thanks!

And if I have two patterns where one is more specific than the other...? which one should come first in the chain?

#### Specific pattern earlier

```R
set_redactor(function (response) {
    response %>%
        gsub_response("https\\://www.ebi.ac.uk/gwas/rest/api/singleNucleotidePolymorphisms/", "snps/") %>%
        gsub_response("https\\://www.ebi.ac.uk/gwas/rest/api/", "gc/")
})
```

#### Specific pattern later

```R
set_redactor(function (response) {
    response %>%
        gsub_response("https\\://www.ebi.ac.uk/gwas/rest/api/", "gc/") %>%
        gsub_response("https\\://www.ebi.ac.uk/gwas/rest/api/singleNucleotidePolymorphisms/", "snps/")
})
```

**Comment by nealrichardson** [comment] 2019-04-17 23:06
They evaluate in order, just as if you were calling `gsub()` on a string, so in your "Specific pattern later" case, I wouldn't expect the second regexp to match anything because the first one will have replaced all `"https://www.ebi.ac.uk/gwas/rest/api/"` with `"gc/"`

**Comment by ramiromagno** [comment] 2019-04-17 23:25
@nealrichardson Thank you for all the help! I've got everything working now :)

**Closed** 2020-12-21 21:55 UTC
